### ISSUE TITLE
List of Available Languages

### ISSUE THREAD

**Issue by beniza** [friendsofagape/mt2414#14]
Create a new API that provides currently available source languages and the Scripture books available in each one of them. The UI team can call this API to list the languages on various client pages.

**Comment by Joel-C-Johnson** [comment]
Done

**Comment by faithfulmaster** [comment]
As discussed in the main channel, @Joel-C-Johnson will hopefully complete the following API's for the above task: 1st API which shows the available languages and versions; 2nd API, wherein the user gives the language and version so that it shows the available books in the given language and version
