### ISSUE TITLE
Generate tokens

### ISSUE THREAD

**Issue by faithfulmaster** [friendsofagape/mt2414#25]
# # User story 
Create an auto generated token list from the source text and store it in the database, so that it can be used in case the tagged token list is unavailable

# # Definition of done 
The administrator will be happy and satisfied, if
 - He is able to provide the tokens for translation as soon as the source is uploaded to the server
 - an end user is able to successfully generate a draft from the source text by submitting the translated tokens (no missing tokens)
 - He will be able to use the tokens even after the source text is updated (in this case the tokens should be updated with the tokens from the updated text or provide the user a way to generate a draft from the same version of the text used for generating the tokens)

**Comment by beniza** [comment]
Assign to: @Joel-C-Johnson
