### ISSUE TITLE
API to log out from session

### ISSUE THREAD

**Issue by bijob89** [friendsofagape/mt2414#47]
From: https://stackoverflow.com/questions/21978658/invalidating-json-web-tokens
I too have been researching this question, and while none of the ideas below are complete solutions, they might help others rule out ideas, or provide further ones.

## 1) Simply remove the token from the client
Obviously this does nothing for server side security, but it does stop an attacker by removing the token from existence (ie. they would have to have stolen the token prior to logout).

## 2) Create a token blacklist
You could store the invalid tokens until their initial expiry date, and compare them against incoming requests. This seems to negate the reason for going fully token based in the first place though, as you would need to touch the database for every request. The storage size would likely be lower though, as you would only need to store tokens that were between logout & expiry time (this is a gut feeling, and is definitely dependent on context).

## 3) Just keep token expiry times short and rotate them often
If you keep the token expiry times at short enough intervals, and have the running client keep track and request updates when necessary, number 1 would effectively work as a complete logout system. The problem with this method, is that it makes it impossible to keep the user logged in between closes of the client code (depending on how long you make the expiry interval).

## Contingency Plans
If there ever was an emergency, or a user token was compromised, one thing you could do is allow the user to change an underlying user lookup ID with their login credentials. This would render all associated tokens invalid, as the associated user would no longer be able to be found.

I also wanted to note that it is a good idea to include the last login date with the token, so that you are able to enforce a relogin after some distant period of time.

In terms of similarities/differences with regards to attacks using tokens, this post addresses the question: http://blog.auth0.com/2014/01/07/angularjs-authentication-with-cookies-vs-token/

**Comment by faithfulmaster** [comment]
Done by @HimanshuBCS from the UI

**Comment by faithfulmaster** [comment]
The logout function implemented on the UI side is not secure. An API should be developed, such that when the user logs out, the authentication token is destroyed from the server itself.

**Comment by faithfulmaster** [comment]
Update JWT token to include the “exp” property

- Import datetime library
- Update line no. 76 : 'exp': datetime.datetime.utcnow() + datetime.timedelta(days=7)
- Line. no. 204: ‘verify_exp’: True

**Comment by beniza** [comment]
We have decided that we will keep the Expiry as 1 day.
