### ISSUE TITLE
Cluster-wise (Pre-defined set of books) download of Tokens

### ISSUE THREAD

**Issue by faithfulmaster** [friendsofagape/mt2414#54]
Give user the benefit of downloading tokens in the form of clusters, so that the number of tokens in the downloaded list, are manageable.

**Comment by faithfulmaster** [comment]
![image](https://user-images.githubusercontent.com/26402465/27032169-1a993516-4f91-11e7-9503-24da9f5c9803.png)

![image](https://user-images.githubusercontent.com/26402465/27032194-484c9520-4f91-11e7-8e81-c18a67951bed.png)

**Comment by Joel-C-Johnson** [comment]
This issue is solved. Created a Cluster API which helps the user to download the token bookwise.
