### ISSUE TITLE
Option to download tokens incrementally

### ISSUE THREAD

**Issue by beniza** [friendsofagape/mt2414#61]
Please add incremental token words download option. 
Option to download token for a selected text, leaving the decision to to the user to select the tokens --to add or omit-- tokens for a specific book.
[SQL example](https://files.slack.com/files-pri/T4F6ZDR8A-F5TBK7751/img_20170614_125243.jpg)

**Comment by beniza** [comment]
Assigning this task to Joel.

**Comment by faithfulmaster** [comment]
This API should incorporate the feature that it will download only those tokens from sourcetext, which have not already been translated in the target language
