### ISSUE TITLE
Split Quotes while generating tokens 

### ISSUE THREAD

**Issue by beniza** [friendsofagape/mt2414#62]
Some quotes and punctuation characters (like ” “) are still present in the tokens. Please update the split code to separate them before generating the codes.

Eg:
‘કબૂતરી’, દે”

**Comment by faithfulmaster** [comment]
Right. These punctuation marks are missing from the regex that we have used for splitting the punctuation marks (they are 4 separate characters: ” “ ‘ ’
@beniza will surely add these to the code.
