### ISSUE TITLE
Split punctuation's from words 

### ISSUE THREAD

**Issue by bijob89** [friendsofagape/mt2414#8]
I am working on this.

**Comment by bijob89** [comment]
I'm working on this.

**Comment by beniza** [comment]
Possible punctuation marks (Devanagari):
!"#$%&\'\\(\\)\\*\\+,-\\./:;<=>\\?\\@\\[\\\\]^_`{|\\}~।

_This list may not me comprehensive. \ is escape char_

**Comment by beniza** [comment]
This is necessary only for the automated token generation. I'm moving this into current sprint and assigning to Samuel

**Comment by faithfulmaster** [comment]
Connected with @bijob89 to use the regular expression: ([!"#$%&'\(\)\*\+,-\.\/:;<=>\?\@\[\]^_`{|\}~।]) and then replace it with " \1 " . This will cause the punctuation marks to be separated from the words in the sourcetext with a whitespace character. Should resolve this issue
